version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: record_store
      POSTGRES_PASSWORD: record_store_pass
      POSTGRES_DB: record_store
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: